id: python.lang.compatibility.python37.python37-compatibility-pdb
pattern: pdb.set_trace(header=$X, ...)
message: pdb.set_trace() with the header argument is only available on Python 3.7+
  and is therefore not backwards compatible. Instead, use set_trace() without the
  header argument.
languages:
- python
severity: ERROR
metadata:
  category: compatibility
  technology:
  - python
  license: Commons Clause License Condition v1.0[LGPL-2.1-only]
  source: https://semgrep.dev/r/python.lang.compatibility.python37.python37-compatibility-pdb
  shortlink: https://sg.run/GeA2
  semgrep.dev:
    rule:
      r_id: 9592
      rv_id: 110325
      rule_id: KxUby2
      version_id: ZRTQNjx
      url: https://semgrep.dev/playground/r/ZRTQNjx/python.lang.compatibility.python37.python37-compatibility-pdb
      origin: community
